version: '2'
services:
  synchronizer:
    image: 'jibraniqbal/product-synchronizer:1.0.0'
    build:
      context: .
    container_name: product-synchronizer
    ports:
      - "8080:8080"
    volumes:
      - ./csvfile:/app/csvfile
    depends_on:
      - product-information-management
    networks:
      - pimnet

  app:
    image: 'jibraniqbal/product-information-management:1.0.0'
    build:
      context: .
    container_name: product-information-management
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - pimnet



  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - pimnet

networks:
  pimnet:
    driver: bridge