# for local development without docker
#pim:
#  file-path: /Users/jibraniqbal/Documents/Hays/path
#  url: http://localhost:8081/products

# for development with docker
pim:
  file-path: /app/csvfile
  url: http://localhost:8081/products

