FROM jibraniqbal/product-information-management
MAINTAINER Jibbu <jibran.iqbal90@gmail.com>
EXPOSE 8081
ENV PORT 8081
COPY product-information-management.jar product-information-management.jar
ENTRYPOINT ["java","-jar","product-information-management.jar"]
